apiVersion: v1
kind: Pod
metadata:
  name: nginx01
  labels:  
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: httpd04
  labels:  
    app: httpd04
spec:
  containers:
  - name: httpd
    image: httpd
 
