apiVersion: v1
kind: ConfigMap
metadata: 
  name: game-demo
data:
 URL: example.com
 SUB_URL: sub.example.com
 DOMAIN: .com
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx06
spec:
  containers:
  - name: nginx
    image: nginx
    env: 
     - name: URL
       value: example.com
       envFrom:
          - ConfigMapRef:
              name: special-config

